// GENERATED by scripts/sync-types.mjs — не редактировать вручную.
// Источник: v0-design-libs/lib/figma-rules/types.ts

/**
 * Канонический контракт правил для Figma-плагина Design Libs Inspector.
 * Этот файл — источник истины. Копируется в репо плагина скриптом sync-types.
 */

export type Severity = 'error' | 'warning' | 'info'

export type CheckType = 'auto' | 'ai' | 'manual'

/** Идентификаторы 22 детерминированных алгоритмов. */
export type DetectorId =
  | 'contrast-wcag'
  | 'contrast-nontext'
  | 'touch-target'
  | 'font-size-min'
  | 'line-height'
  | 'line-length'
  | 'grid-snap'
  | 'choice-count'
  | 'palette-size'
  | 'font-sizes-scale'
  | 'font-families'
  | 'radius-consistency'
  | 'stroke-consistency'
  | 'shadow-consistency'
  | 'disabled-visible'
  | 'dark-theme-purity'
  | 'missing-label'
  | 'button-min-size'
  | 'target-spacing'
  | 'focus-visible'
  | 'letter-spacing'
  | 'text-on-image'

export interface DetectorConfig {
  id: DetectorId
  /** Произвольные параметры алгоритма (пороги, платформа и т.п.) */
  params?: Record<string, number | string | boolean>
}

export type RuleCategory =
  // UI-принципы
  | 'Иерархия'
  | 'Типографика'
  | 'Цвет и контраст'
  | 'Пространство'
  | 'Компоненты'
  | 'Состояния'
  | 'Тёмная тема'
  | 'Формы'
  // UX-законы
  | 'Когнитивная нагрузка'
  | 'Искажения и эвристики'
  | 'Принятие решений'
  | 'Память'
  | 'Внимание'
  | 'Мотивация и поведение'
  | 'Убеждение и влияние'
  | 'Восприятие'
  | 'Эмоции'
  | 'Гештальт'
  | 'Социальная психология'
  | 'Взаимодействие'
  | 'Вознаграждение'
  | 'Ментальные модели'
  | 'Производительность'
  | 'Поведение'

export type RuleSource = 'ui-guide' | 'ux-law'

export interface FigmaRule {
  /** Стабильный ID из исходного каталога (hicks-law, wcag-contrast, …) */
  id: string
  source: RuleSource
  nameRu: string
  nameEn: string
  category: RuleCategory
  categoryEn: string
  summary: string
  summaryEn?: string
  description: string
  descriptionEn?: string
  /** Пункты применения — короткие «что делать» */
  application: string[]
  example?: string
  antiPattern?: string
  /** Важность 1–5 (для UX-законов); для UI-принципов приводится к 3 по умолчанию */
  impact: 1 | 2 | 3 | 4 | 5
  severity: Severity
  checkType: CheckType
  /** Есть только для checkType === 'auto' */
  detector?: DetectorConfig
  tags: string[]
  relatedIds?: string[]
  /** Ссылка на страницу правила в design-libs */
  docUrl: string
}

export interface FigmaRulesResponse {
  version: string
  updatedAt: string
  count: number
  rules: FigmaRule[]
}
