#!/usr/bin/env node
/**
 * Эмбеддит snapshot каталога правил в бандл плагина.
 * Порядок источников:
 *   1. process.env.RULES_URL
 *   2. http://localhost:3000/api/figma-rules/v1
 *   3. https://design-libs.vercel.app/api/figma-rules/v1
 *   4. Fallback: существующий src/shared/rules-snapshot.json
 *
 * Артефакты:
 *   - src/shared/rules-snapshot.json  (коммитится)
 *   - src/shared/rules-bundle.ts      (GENERATED, коммитится)
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const SNAPSHOT = resolve(ROOT, 'src/shared/rules-snapshot.json')
const BUNDLE = resolve(ROOT, 'src/shared/rules-bundle.ts')

const SOURCES = [
  process.env.RULES_URL,
  'http://localhost:3000/api/figma-rules/v1',
  'https://design-libs.vercel.app/api/figma-rules/v1',
].filter(Boolean)

async function tryFetch(url) {
  const controller = new AbortController()
  const t = setTimeout(() => controller.abort(), 5000)
  try {
    const res = await fetch(url, { signal: controller.signal, headers: { Accept: 'application/json' } })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const json = await res.json()
    if (!json?.count || !Array.isArray(json?.rules)) throw new Error('Invalid payload')
    return { source: url, payload: json }
  } catch (err) {
    return { source: url, error: err.message }
  } finally {
    clearTimeout(t)
  }
}

async function loadFallback() {
  try {
    const raw = await readFile(SNAPSHOT, 'utf8')
    return { source: `fallback:${SNAPSHOT}`, payload: JSON.parse(raw) }
  } catch {
    return null
  }
}

let result = null
for (const url of SOURCES) {
  const r = await tryFetch(url)
  if (r.payload) { result = r; break }
  console.log(`[embed-rules] skip ${url}: ${r.error}`)
}
if (!result) {
  result = await loadFallback()
  if (!result) {
    console.error('❌ Не удалось получить каталог правил ни из одного источника и нет локального snapshot.')
    process.exit(1)
  }
}

const { source, payload } = result
if (!payload.count || payload.count < 50) {
  console.error(`❌ Подозрительно мало правил (${payload.count}). Прерываю сборку.`)
  process.exit(1)
}

const bundleTs =
  '// GENERATED by scripts/embed-rules.mjs — не редактировать вручную.\n' +
  `// Источник: ${source}\n` +
  `// Встроено: ${new Date().toISOString()}\n\n` +
  `import type { FigmaRulesResponse } from './rules-types'\n\n` +
  `export const BUNDLED_RULES: FigmaRulesResponse = ${JSON.stringify(payload, null, 2)}\n` +
  `\nexport const BUNDLED_AT = ${JSON.stringify(new Date().toISOString())}\n` +
  `export const BUNDLED_SOURCE = ${JSON.stringify(source)}\n`

await mkdir(dirname(BUNDLE), { recursive: true })
await writeFile(SNAPSHOT, JSON.stringify(payload, null, 2) + '\n', 'utf8')
await writeFile(BUNDLE, bundleTs, 'utf8')

const sizeKb = (Buffer.byteLength(bundleTs, 'utf8') / 1024).toFixed(1)
console.log(`✅ embed-rules: count=${payload.count} source=${source} bundleSize=${sizeKb}KB`)
