#!/usr/bin/env node
/**
 * Копирует канонические типы из v0-design-libs в репо плагина.
 * Запускается перед сборкой. CI падает, если исходник отсутствует.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const SRC = resolve(__dirname, '../../v0-design-libs/lib/figma-rules/types.ts')
const DST = resolve(__dirname, '../src/shared/rules-types.ts')

const BANNER =
  '// GENERATED by scripts/sync-types.mjs — не редактировать вручную.\n' +
  '// Источник: v0-design-libs/lib/figma-rules/types.ts\n\n'

try {
  const raw = await readFile(SRC, 'utf8')
  await mkdir(dirname(DST), { recursive: true })
  await writeFile(DST, BANNER + raw, 'utf8')
  console.log(`✅ sync-types: ${SRC} → ${DST}`)
} catch (err) {
  console.error('❌ sync-types failed:', err.message)
  process.exit(1)
}
